changes added

diff --git a/Jenkins_backup_2 b/Jenkins_backup_2
--- a/Jenkins_backup_2
+++ b/Jenkins_backup_2
@@ -9,17 +9,20 @@ pipeline{
     }
 
     environment {
-        AWS_S3_BUCKET = 'cicdbeansnew'
-        AWS_EB_APP_NAME = 'emp-my-app'
-        AWS_EB_ENVIRONMENT = 'Emp-my-app-env'
+        AWS_S3_BUCKET = 'cicdbeans3'
+        AWS_EB_APP_NAME = 'employee-test'
+        AWS_EB_ENVIRONMENT = 'Employee-test-env'
         AWS_EB_APP_VERSION = "${BUILD_ID}"
         ARTIFACT_NAME = "employeemanager-v${BUILD_ID}.jar"
         COSIGN_PASSWORD = credentials('cosign-password') 
         COSIGN_PRIVATE_KEY = credentials('cosign-private-key') 
         COSIGN_PUBLIC_KEY = credentials('cosign-public-key')
         SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
-        SEMGREP_PR_ID = "${env.CHANGE_ID}" 
-        CR_TOKEN = credentials('cr_cred')    
+        SEMGREP_PR_ID = "${env.CHANGE_ID}"
+        AZURE_SUBSCRIPTION_ID = credentials('azure-subscription-id')
+        AZURE_CLIENT_ID = credentials('azure-client-id')
+        AZURE_CLIENT_SECRET = credentials('azure-client-secret')
+        AZURE_TENANT_ID = credentials('azure-tenant-id')
     }
 
     stages{
@@ -43,7 +46,6 @@ pipeline{
                                     sh 'mvn build-helper:parse-version versions:set \
                                         -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                                         versions:commit'
-                                  //  incrementPatchVersion()
                                     def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                                     def version = matcher[1][1]       
                                     env.IMAGE_VERSION = "$version-$BUILD_NUMBER"
@@ -139,7 +141,7 @@ pipeline{
                                                                 -Dsonar.projectName=employee \
                                                                 -Dsonar.projectVersion=1.0 \
                                                                 -Dsonar.sources=src/ \
-                                                                -Dsonar.host.url=http://172.48.16.220/ \
+                                                                -Dsonar.host.url=http://172.48.16.144/ \
                                                                 -Dsonar.java.binaries=target/test-classes/com/employees/employeemanager/ \
                                                                 -Dsonar.jacoco.reportsPath=target/jacoco.exec \
                                                                 -Dsonar.junit.reportsPath=target/surefire-reports/ \
@@ -155,15 +157,14 @@ pipeline{
                                                 }         
                                     }
                                 },
-                                "Semgrep": {                     
+                                "Semgrep": {
+                                    dir('employeemanagerfrontend') {
                                            sh '''
-                                                    docker pull semgrep/semgrep && \
-                                                    docker run \
-                                                        -e SEMGREP_APP_TOKEN=$SEMGREP_APP_TOKEN \
-                                                        -e SEMGREP_PR_ID=$SEMGREP_PR_ID \
-                                                        -v "$(pwd):$(pwd)" --workdir $(pwd) \
-                                                    semgrep/semgrep semgrep ci --json --output semgrep.json
-                                              '''   
+                                                    pip3 install --user --upgrade semgrep
+                                                    export PATH=$PATH:$HOME/.local/bin
+                                                    semgrep ci --json --output semgrep.json
+                                              '''
+                                    }
                                 }
 
                     )
@@ -171,34 +172,41 @@ pipeline{
             }
             post {
                     always {
-                        archiveArtifacts artifacts: '**/semgrep.json', allowEmptyArchive: true
+                        archiveArtifacts artifacts: '**/employeemanagerfrontend/semgrep.json', allowEmptyArchive: true
                     }
                 }   
 
         }
 
-
-
-        stage("Deploy to stage bean"){
-           steps {
-            script{
-                dir('employeemanager') {
-                    env.JAR_FILE = sh(script: "ls target/employeemanager-*.jar", returnStdout: true).trim()
-                    echo "Found JAR File: ${env.JAR_FILE}"
-                    withAWS(credentials: 'awsbean', region: 'us-east-1') {
-                     //   sh '''
-                    //        pip3 install --user urllib3==1.26.16
-                   //         pip3 install --user --upgrade awscli botocore
-                   //         export PATH=$HOME/.local/bin:$PATH
-                   //     '''
-                        sh "aws s3 cp ${env.JAR_FILE} s3://$AWS_S3_BUCKET/$ARTIFACT_NAME"
-                        sh 'aws elasticbeanstalk create-application-version --application-name $AWS_EB_APP_NAME --version-label $AWS_EB_APP_VERSION --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ARTIFACT_NAME'
-                        sh 'aws elasticbeanstalk update-environment --application-name $AWS_EB_APP_NAME --environment-name $AWS_EB_ENVIRONMENT --version-label $AWS_EB_APP_VERSION'
+        stage("Upload Artifacts"){
+            steps {
+                script {
+                        dir('employeemanager') {
+                                env.JAR_FILE = sh(script: "ls target/employeemanager-*.jar", returnStdout: true).trim()
+                                echo "Found JAR File: ${env.JAR_FILE}"
+                                nexusArtifactUploader(
+                                            nexusVersion: 'nexus3',
+                                            protocol: 'http',
+                                            nexusUrl: '172.48.16.120:8081',
+                                            groupId: 'QA',
+                                            version: "${BUILD_ID}",
+                                            repository: 'employee-repo',
+                                            credentialsId: 'nexus',
+                                            artifacts: [
+                                                    [artifactId: 'employeemgmt',
+                                                    classifier: '',
+                                                    file: "${env.JAR_FILE}",
+                                                    type: 'jar']
+                                                ]
+                                )
+                            }               
+                        }
+                    }
                 }
-            }
-            }   
-           }
-        }
+
+
+
+
 
         stage("Vulnerability Scan - Docker") {
             steps {
@@ -349,7 +357,7 @@ pipeline{
                 }
 
 
-         stage("change image in kubeconfig") {
+        stage("change image in kubeconfig") {
             steps {
                 script {
                     parallel(
@@ -375,8 +383,8 @@ pipeline{
                                 "Frontend Reports Upload": {
                                     dir('employeemanagerfrontend') {
                                         script {
-                                            // python3 upload-reports.py semgrep.json 
-                                            sh '''                                           
+                                            sh '''
+                                                python3 upload-reports.py semgrep.json 
                                                 python3 upload-reports.py njsscan.sarif
                                                 python3 upload-reports.py retire.json
                                             '''
@@ -400,7 +408,7 @@ pipeline{
 
         }
 
-         stage("Vulnerability Scan - kubernetes") {
+        stage("Vulnerability Scan - kubernetes") {
             steps {
                 script {
                         parallel (
@@ -419,7 +427,7 @@ pipeline{
                                             wait
                                        '''                           
                             },
-                           "kubescape": {
+                            "kubescape": {
                                 dir('kustomization') {
                                         script {
                                             sh '''
@@ -432,14 +440,27 @@ pipeline{
                     }
             }
         }
+
         stage("Kubernetes Apply") {
             steps {
                 script {
-                         withKubeConfig([credentialsId: 'kubeconfig']) {
-                            sh 'kubectl get nodes'
-                        }
+                            sh "az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID"
+                            sh "az aks get-credentials --resource-group aks-rg1 --name aks-demo --overwrite-existing"
+                            sh '''
+                                        if [ ! -f kubernetes-script.sh ]; then
+                                            echo "kubernetes-script.sh file is missing!" >&2
+                                            exit 1
+                                        fi
+                                        chmod +x kubernetes-script.sh
+                                
+                            '''
+                         //   sh "./kubernetes-script.sh"
+                            sh "kubectl config use-context aks-demo"
+                            sh "kubectl config current-context"
+                            sh "kubectl apply -k kustomization/"
+                            sh "kubectl get all"
 
-                    }
+                        }
                 }
             
         }
@@ -447,26 +468,29 @@ pipeline{
         stage ("kubernetes cluster check") {
             steps {
                 script {
-                        withKubeConfig([credentialsId: 'kubeconfig']) {
-                                parallel (
-                                        "kubernetes CIS benchmark": {
-                                            sh '''
-                                                kubescape scan framework all
-                                            '''
-                                        },
-                                        "kubernetes cluster scan": {
-                                            sh '''
-                                                kubescape scan
-                                            '''
-                                        },
-                                        "kubenetes resource scan": {
-                                            sh '''
-                                                kubescape scan workload Deployment/employee-frontend --namespace employee
-                                                kubescape scan workload service/employee-frontend-service --namespace employee
-                                            '''
-                                        }
-                                )
+                        sh '''
+                            kubectl config use-context aks-demo
+                        '''
+                    parallel (
+                        "kubernetes CIS benchmark": {
+                            sh '''
+                                kubescape scan framework all
+                            '''
+                        },
+                        "kubernetes cluster scan": {
+                             sh '''
+                                kubescape scan
+                            '''
+                        },
+                        "kubenetes resource scan": {
+                             sh '''
+                                kubescape scan workload Deployment/employee-backend 
+                                kubescape scan workload service/employee-backend-service 
+                            '''
                         }
+                    )
+                            
+
                 }
             }
         }
